mode: "LS"

HOLS:
  dataset: "Rice31"
  data_type: "fb100"
  binary: true
  kn: 15
  noise: 0
  ε: 1e-6
  tolerance: 1e-5
  num_trials: 10
  balanced: true
  α: [0.1]
  β: [0.1]
  percentage_of_known_labels: [0.2]
  weight_function: "cosine_angle"
  mixing_functions: "f_max"


LS:
  α:
    - .1
  ε: 1e-6
  kn: 15
  noise: 0
  tolerance: 1e-5
  dataset: "Caltech36"
  binary: true
  percentage_of_known_labels: [0.15, 0.2, 0.25, 0.3]
  balanced: true
  data_type: "fb100"
  num_trials: 5


both:
  α:
    - .1
    - .2
    - 5
  β:
    - .1
  ε: 1e-6
  kn: 15
  noise: 0
  tolerance: 1e-5
  dataset: iris
  distance: cosine_angle
  binary: false
  percentage_of_known_labels:
    - .1
  balanced: false
  data_type: points
  num_trials: 5
  mixing_functions: f1, f2, f4, f3, f_max
